__author__ = "Eduardo R. de Velasco"
__copyright__ = "Copyright 2023"
__credits__ = ["Eduardo R. de Velasco"]
__license__ = "MIT"
__version__ = "0.1"
__maintainer__ = "Eduardo R. de Velasco"
__email__ = "ervelasco12@yahoo.es"
__status__ = "Development"
__url__ = 'https://github.com/ervelasco/darwinex-data'
